services:
  floodlight-webui:
    build:
      context: ..
      dockerfile: docker-floodlight-webui/Dockerfile
    container_name: floodlight_webui_lab
    ports:
      - "6655:6653"
      - "8082:8080"
    restart: "no"
    volumes:
      - ../floodlight-webui:/opt/floodlight/target/web  # adjust path to wherever ant's output/served dir actually is