services:
  floodlight-webui:
    build:
      context: ..
      dockerfile: floodlight-webui/Dockerfile
    container_name: floodlight_webui
    ports:
      - "6655:6653"
      - "8082:8080"
    restart: "no"